### PR TITLE
Bump version and document release process

### PR DESCRIPTION
**Pull request by allisonnicoledeal**
Wanted to release a new updated with the new `cancel_event` method, which is needed for deleting input devices on the Propeller side.

I don't know what I'm doing here as far as the release goes, but wanted to start documenting..what else is needed?

Fixes https://github.com/cbsinteractive/propeller/issues/1529

### CODE REVIEW

**Review by igorsobreira — APPROVED** [review]

**Comment by igorsobreira** [comment]
@allisonnicoledeal I believe we need to build first:
```
poetry build
poetry publish
```
or
```
poetry publish --build
```

**Comment by igorsobreira** [comment]
@allisonnicoledeal just realized we have a makefile, here is an idea:
```makefile
release: clean-build
    poetry publish --build
```

I haven't tried yet 🙂

**Comment by rafaelcaricio** [comment]
That is basically it. Later we can create a user in PyPI just for publishing releases and create a Github workflow to do it automatically based on tags. https://github.com/cbsinteractive/elemental/issues/74

**Comment by allisonnicoledeal** [comment]
> @allisonnicoledeal just realized we have a makefile, here is an idea:
> 
> ```makefile
> release: clean-build
>     poetry publish --build
> ```
> 
> I haven't tried yet 🙂

Success! 9d5b8ba405ba24e20ea0aa0671a154ab83cb80b1

**Pull request merged**
